/**
 * Player播放器状态定义
 */

typedef enum _QP_PLAYER_STATUS
{
  QP_PLAYER_STATUS_NOT_READY,
  QP_PLAYER_STATUS_READY,
  QP_PLAYER_STATUS_PLAYING,
  QP_PLAYER_STATUS_EOS,
  QP_PLAYER_STATUS_PAUSE,
  QP_PLAYER_STATUS_BUFFER_LOADING,
} QP_PLAYER_STATUS;